# This file was generated by GoReleaser. DO NOT EDIT.
cask "cuttle" do
  version "0.7.0"

  on_macos do
    on_intel do
      sha256 "a5662dec784aec446da98b731d9eea2d5b9b2ed4e6eacdca5793dbee4f8b92bc"
      url "https://github.com/glim-sh/cuttle/releases/download/v#{version}/cuttle_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "7de8a6e57f37ee52722b792537f5bdf66d67fde80334c098a400bb70fcfc0846"
      url "https://github.com/glim-sh/cuttle/releases/download/v#{version}/cuttle_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "1caa754075c5b4c16360c23432607758c9d784d129d95f01e8c322613b9baf7a"
      url "https://github.com/glim-sh/cuttle/releases/download/v#{version}/cuttle_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "a4d23cb0e8263ed81a8b9ed2b8c4f94901f3646d2930076324add8cb008dec4e"
      url "https://github.com/glim-sh/cuttle/releases/download/v#{version}/cuttle_#{version}_linux_arm64.tar.gz"
    end
  end

  name "cuttle"
  desc "Host CLI for the cuttle stealth-Chromium CDP farm"
  homepage "https://github.com/glim-sh/cuttle"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "cuttle"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/cuttle"]
    end
  end

  # No zap stanza required

end
