# This file was generated by GoReleaser. DO NOT EDIT.
cask "cuttle" do
  version "0.10.0"

  on_macos do
    on_intel do
      sha256 "a46fa003beeb4bba0b783781fe2465a4039c53336f0ad339c7f30a711c6a4d19"
      url "https://github.com/glim-sh/cuttle/releases/download/v#{version}/cuttle_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "89486cf98b5e5f454e2f4ed0893993a50b053707b5b815efdd8bbee59e569ea3"
      url "https://github.com/glim-sh/cuttle/releases/download/v#{version}/cuttle_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "f504197be188af5228d29042a82a3ee48ebeae69886e811b538f1c6e3822fc0f"
      url "https://github.com/glim-sh/cuttle/releases/download/v#{version}/cuttle_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "bbea3f149d6e94546da90212bbce362f093e007d9b6a9a512c19ad61824100b1"
      url "https://github.com/glim-sh/cuttle/releases/download/v#{version}/cuttle_#{version}_linux_arm64.tar.gz"
    end
  end

  name "cuttle"
  desc "Host CLI for the cuttle stealth-Chromium CDP farm"
  homepage "https://github.com/glim-sh/cuttle"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "cuttle"

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/cuttle"] if OS.mac?
  end

  # No zap stanza required

  caveats <<~EOS
    cuttle ships as an unsigned binary; its quarantine attribute is stripped
    on install so it runs without a Gatekeeper prompt.
  EOS
end
