# This file was generated by GoReleaser. DO NOT EDIT.
cask "cuttle" do
  version "0.9.1"

  on_macos do
    on_intel do
      sha256 "316959d33d04b58f6c74d7b2cceeb503902fcb7b43c7819e018ab31eb9741b19"
      url "https://github.com/glim-sh/cuttle/releases/download/v#{version}/cuttle_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "d4d7f9464ffe2e5b79bf3a11c4179c06925da0ae8e497998d3cb31223444579c"
      url "https://github.com/glim-sh/cuttle/releases/download/v#{version}/cuttle_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "f775bfdff5788176c09291c80b57e4a7ab806a310a11f2f066f879dcc3e8e50e"
      url "https://github.com/glim-sh/cuttle/releases/download/v#{version}/cuttle_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "7b5da6d23668764bd2f0e0d0e51930bbbd385f5e1cbffd392469f8add7976ee1"
      url "https://github.com/glim-sh/cuttle/releases/download/v#{version}/cuttle_#{version}_linux_arm64.tar.gz"
    end
  end

  name "cuttle"
  desc "Host CLI for the cuttle stealth-Chromium CDP farm"
  homepage "https://github.com/glim-sh/cuttle"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "cuttle"

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/cuttle"] if OS.mac?
  end

  # No zap stanza required

  caveats <<~EOS
    cuttle ships as an unsigned binary; its quarantine attribute is stripped
    on install so it runs without a Gatekeeper prompt.
  EOS
end
