# This file was generated by GoReleaser. DO NOT EDIT.
cask "frisk" do
  version "0.4.1"

  on_macos do
    on_arm do
      sha256 "bc92c6475e1471157ade699d587563ec710436c864d1ae08b83e062d81a77fd0"
      url "https://github.com/tenequm/frisk/releases/download/v#{version}/frisk_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "fea71df10062ce00484f30d62bbf116c4c31bc3869737679e2296d9378c3b7e4"
      url "https://github.com/tenequm/frisk/releases/download/v#{version}/frisk_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "d1af6f45a4c606cbd081609f47fbe6911b08881867542395b2520ead6681b80a"
      url "https://github.com/tenequm/frisk/releases/download/v#{version}/frisk_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "095b0e1acfa07cc6e491e16ae61ae66fac14bf702dfc79874e7c8bb5d39d1bb6"
      url "https://github.com/tenequm/frisk/releases/download/v#{version}/frisk_#{version}_linux_amd64.tar.gz"
    end
  end

  name "frisk"
  desc "Claude Code PreToolUse hook that gates Bash commands"
  homepage "https://github.com/tenequm/frisk"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "frisk"

  # No zap stanza required
end
