# This file was generated by GoReleaser. DO NOT EDIT.
cask "frisk" do
  version "0.4.3"

  on_macos do
    on_arm do
      sha256 "b9d7136f4a80ab94fde718011d2dd1de630c988bec87268e0a0e378e9be6ac3c"
      url "https://github.com/tenequm/frisk/releases/download/v#{version}/frisk_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "37eb8c1908a23ed486cbf88b926e61bd5d25356fadc54844647df5de5e46ca52"
      url "https://github.com/tenequm/frisk/releases/download/v#{version}/frisk_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "8d2a58713ad329df5fe6e014e391458d89a55d0c880d70e521227c962d8b416c"
      url "https://github.com/tenequm/frisk/releases/download/v#{version}/frisk_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "d57bd6f3e873851233d96b3b3282b43c7ebc11a10b11ecd2318086f5d1b639d3"
      url "https://github.com/tenequm/frisk/releases/download/v#{version}/frisk_#{version}_linux_amd64.tar.gz"
    end
  end

  name "frisk"
  desc "Claude Code PreToolUse hook that gates Bash commands"
  homepage "https://github.com/tenequm/frisk"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "frisk"

  # No zap stanza required
end
