# This file was generated by GoReleaser. DO NOT EDIT.
cask "frisk" do
  version "0.1.4"

  on_macos do
    on_arm do
      sha256 "3dbcf5032d73fa78524b7e8f68e18453d93810486b1dc5f22b721cafbfbac176"
      url "https://github.com/tenequm/frisk/releases/download/v#{version}/frisk_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "a1183e3f4e7569b04531b52a6e156585dad28d4552ce340c95e7e5fa65258682"
      url "https://github.com/tenequm/frisk/releases/download/v#{version}/frisk_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "c984ff9ae6cbac00323501f0314243d0f1ceef0e17b3f757786445c9811b99f9"
      url "https://github.com/tenequm/frisk/releases/download/v#{version}/frisk_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "39cf4cfb286d0be27a252d61c4c6595810dde9bba1918075c68ef61da352fe0f"
      url "https://github.com/tenequm/frisk/releases/download/v#{version}/frisk_#{version}_linux_amd64.tar.gz"
    end
  end

  name "frisk"
  desc "Claude Code PreToolUse hook that gates Bash commands"
  homepage "https://github.com/tenequm/frisk"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "frisk"

  # No zap stanza required
end
