# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Pond < Formula
  desc "Lossless storage and hybrid search for AI agent sessions, across every agentic client."
  homepage "https://github.com/tenequm/pond"
  version "0.2.2"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/tenequm/pond/releases/download/v0.2.2/pond-aarch64-apple-darwin.tar.xz"
      sha256 "d1aece84b915d9aa97d2776f468198582cdb6e7c90918f6332d9d7dbb751865f"

      define_method(:install) do
        bin.install "pond"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/tenequm/pond/releases/download/v0.2.2/pond-x86_64-unknown-linux-gnu.tar.xz"
      sha256 "a010dbbdfaec98670f40379287d471065ddab8b4b9e1b742fa810c5f13f770c3"
      define_method(:install) do
        bin.install "pond"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/tenequm/pond/releases/download/v0.2.2/pond-aarch64-unknown-linux-gnu.tar.xz"
      sha256 "ed479590a5af203bdd62bb3a6b917e5576ed16fbb69a8c0708a8b1a5d7aa2265"
      define_method(:install) do
        bin.install "pond"
      end
    end
  end
end
