# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Pond < Formula
  desc "Lossless storage and hybrid search for AI agent sessions, across every agentic client."
  homepage "https://github.com/tenequm/homebrew-tap"
  version "0.2.7"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/tenequm/homebrew-tap/releases/download/pond-v0.2.7/pond-aarch64-apple-darwin.tar.xz"
      sha256 "038f9b8dafd8258ebfc12aabcef286c6e731b90831436301effb021f63c231d8"

      define_method(:install) do
        bin.install "pond"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/tenequm/homebrew-tap/releases/download/pond-v0.2.7/pond-x86_64-unknown-linux-gnu.tar.xz"
      sha256 "b3f4dc8b8fea2f83990b23d181e2808e62909c9a0859a0e52617c430ed9db95a"
      define_method(:install) do
        bin.install "pond"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/tenequm/homebrew-tap/releases/download/pond-v0.2.7/pond-aarch64-unknown-linux-gnu.tar.xz"
      sha256 "dbf1120c0713c56f874c9d74f7c74119c95671603bf6185673c72c1aeee3ae00"
      define_method(:install) do
        bin.install "pond"
      end
    end
  end
end
